import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "Entropy",
  description: "Generated by create next app",
};

export default function EntropyPage() {
  const worldKey = 'entropy';

  return (
    <>
      <Suspense>
        <World worldKey={worldKey} />
      </Suspense>
    </>
  )
}