import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "엔트로피 체제",
  description: "Generated by create next app",
};

export default function EntropyPage() {
  return (
    <Suspense>
      <World worldKey='entropy' />
    </Suspense>
  )
}