import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "희생 기반 체제",
  description: "Generated by create next app",
};

export default function SacrificePage() {
  return (
    <Suspense>
      <World worldKey="sacrifice" />
    </Suspense>
  )
}