import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "Pizza Shoot",
  description: "Generated by create next app",
};

export default function SacrificePage() {
  const worldKey = 'sacrifice'

  return (
    <>
      <Suspense>
        <World worldKey={worldKey} />
      </Suspense>
    </>
  )
}