import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "희생 기반 체제",
  description: "Generated by create next app",
};

export default function SacrificePage() {
  return (
    <>
      <Suspense>
        <World worldKey="sacrifice" />
      </Suspense>
      <audio controls autoPlay className="absolute top-0 left-0">
        <source src="/audio/entropy_bg.mp3" />
      </audio>
    </>
  )
}