import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "On Time",
  description: "Generated by create next app",
};

export default function TimePage() {
  const worldKey = 'time';

  return (
    <>
      <Suspense>
        <World worldKey={worldKey} />
      </Suspense>

    </>
  )
}