import World from "@/app/components/World";
import { Suspense } from "react";

export const metadata = {
  title: "시간 기반 체제",
  description: "Generated by create next app",
};

export default function TimePage() {
  return (
    <Suspense>
      <World worldKey="time" />
    </Suspense>
  )
}