import InterviewForms from "@/app/components/home/interview/InterviewForms";
import InterviewScene from "@/app/components/home/interview/InterviewScene";

export const metadata = {
  title: "인터뷰",
  description: "Generated by create next app",
};

export default function InterviewPage() {
  return (
    <main className="absolute left-0 top-0 w-screen h-screen flex flex-col items-center justify-center gap-4">
      <InterviewScene />
      <InterviewForms />
    </main>
  )
}