import InterviewScene from "@/app/components/maps/interview/InterviewScene";
import InterviewUi from "@/app/components/maps/interview/InterviewUi";
import Scene from "@/app/components/util/Scene";
import { Suspense } from "react";

export const metadata = {
  title: "인터뷰",
  description: "Generated by create next app",
};

export default function InterviewPage() {
  return (
    <main className="absolute left-0 top-0 w-screen h-screen">
      <Scene>
        <InterviewScene />
      </Scene>
      <Suspense>
        <InterviewUi />
      </Suspense>
    </main>
  )
}