import type { Metadata } from "next";
import "./globals.css";
import { nanumGothicCoding, nanumGothicCodingBold } from "./lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nanumGothicCodingBold.className} ${nanumGothicCoding.className} antialiased font-mono flex items-center justify-center w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  );
}